version: '3.8'
services:
  t-jobs:
    build: .
    depends_on:
      - mysql
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/t_jobs

    ports:
      - "8080:8080"
    restart: always

  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
      - MYSQL_DATABASE=t_jobs
    volumes:
      - 'D:\\T-Jobs\\sql_conf:/docker-entrypoint-initdb.d'