version: '3.8'
services:
  t-jobs:
    build: .
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/t_jobs?useUnicode=true&character_set_server=utf8mb4
    ports:
      - "8080:8080"
    restart: always

  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
      - MYSQL_DATABASE=t_jobs
      - MYSQL_CHARSET=utf8mb4
      - MYSQL_COLLATION=utf8mb4_unicode_ci
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - '.\init.sql:/docker-entrypoint-initdb.d/init.sql'